//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformaEducationala.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medie
    {
        public int MedieId { get; set; }
        public double Valoare { get; set; }
        public int Semestru { get; set; }
        public int MaterieId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Materie Materie { get; set; }
        public virtual Utilizator Utilizator { get; set; }
    }
}
