//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformaEducationala.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Objects;

    public partial class Utilizator
    {
        private ObjectResult<GetUtilizator_Result> user;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizator()
        {
            this.Absentas = new HashSet<Absenta>();
            this.Medies = new HashSet<Medie>();
            this.Notas = new HashSet<Nota>();
            this.Clasas = new HashSet<Clasa>();
            this.Materies = new HashSet<Materie>();
            this.Clasas1 = new HashSet<Clasa>();
            this.Clasas2 = new HashSet<Clasa>();
        }

        public Utilizator(ObjectResult<GetUtilizator_Result> user)
        {
            this.user = user;
        }

        public int UtilizatorId { get; set; }
        public string Nume { get; set; }
        public string NumeUtilizator { get; set; }
        public string Parola { get; set; }
        public int TipUtilizatorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absenta> Absentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medie> Medies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Notas { get; set; }
        public virtual TipUtilizator TipUtilizator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasa> Clasas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materie> Materies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasa> Clasas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasa> Clasas2 { get; set; }

    }
}
